### PR TITLE
Update paket to address TLS deprecation

### PR DESCRIPTION
**Pull request by forki**
:wave: GitHub disabled TLS 1.0 and TLS 1.1 on February 22nd, which affected Paket and needs to be updated to 5.142 or later.

You can read more about this on the [GitHub Engineering blog](https://githubengineering.com/crypto-removal-notice/).

The update to Paket is explained here: https://github.com/fsprojects/Paket/pull/3066

The work to update Paket in the wild is occurring here: https://github.com/fsprojects/Paket/issues/3068

### CODE REVIEW

**Comment by aabenoja** [comment]
Thank you for the pull request. Unfortunately, `paket` is no longer actively used in any part of the build process. This is cleanup that I have forgotten to follow up on now that I've converted the project to .net core.

**Comment by forki** [comment]
Yeah. This was automated process and there are obviously a couple of false positives ;-)

Anyway even for .NET core there are very good reasons to go with paket ;-)

**Comment by aabenoja** [comment]
For now I'm going back to the simplicity of the `dotnet cli` to handle my nuget restoration. There are simply too few packages in this project to pull down that I don't need paket's better caching mechanisms. I'll revisit this once the project gets more complicated.

**Comment by forki** [comment]
Yeah wasn't meant that seriously. Good luck with the project and sorry for
the false positive.

Am 28.02.2018 18:16 schrieb "Alex Abenoja" <notifications@github.com>:

For now I'm going back to the simplicity of the dotnet cli to handle my
nuget restoration. There are simply too few packages in this project to
pull down that I don't need paket's better caching mechanisms. I'll revisit
this once the project gets more complicated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aabenoja/Cake.Parallel/pull/5#issuecomment-369311574>,
or mute the thread

**Pull request closed without merging**
